apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  annotations:
    run.googleapis.com/ingress: all
    run.googleapis.com/ingress-status: all
    run.googleapis.com/urls: '["https://manage-tokens-12002195951.us-central1.run.app","https://manage-tokens-vccbnr2zwa-uc.a.run.app"]'
  labels:
    cloud.googleapis.com/location: us-central1
  name: manage-tokens
  namespace: '12002195951'
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/maxScale: '20'
        run.googleapis.com/client-name: gcloud
        run.googleapis.com/client-version: 530.0.0
        run.googleapis.com/startup-cpu-boost: 'true'
      labels:
        client.knative.dev/nonce: hflqrpiaxg
        run.googleapis.com/startupProbeType: Default
    spec:
      containerConcurrency: 80
      containers:
      - env:
        - name: GCP_PROJECT
          value: onlyjobs-465420
        - name: GOOGLE_OAUTH_CLIENT_ID
          valueFrom:
            secretKeyRef:
              key: latest
              name: GOOGLE_OAUTH_CLIENT_ID
        - name: GOOGLE_OAUTH_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              key: latest
              name: GOOGLE_OAUTH_CLIENT_SECRET
        - name: GOOGLE_OAUTH_REDIRECT_URI
          valueFrom:
            secretKeyRef:
              key: latest
              name: GOOGLE_OAUTH_REDIRECT_URI
        image: gcr.io/onlyjobs-465420/manage-tokens
        ports:
        - containerPort: 8080
          name: http1
        resources:
          limits:
            cpu: 1000m
            memory: 1Gi
        startupProbe:
          failureThreshold: 1
          periodSeconds: 240
          tcpSocket:
            port: 8080
          timeoutSeconds: 240
      serviceAccountName: 12002195951-compute@developer.gserviceaccount.com
      timeoutSeconds: 300
  traffic:
  - latestRevision: true
    percent: 100
