#!/bin/bash

echo "🔧 Fixing OAuth Client Configuration"
echo "===================================="

PROJECT_ID="onlyjobs-465420"
CLIENT_ID="12002195951-2gqc8k0m72s9g7r3kfgb3ireli1mpi40.apps.googleusercontent.com"

echo "❌ Current issues found in OAuth URL:"
echo "1. Client ID has newline character (malformed)"
echo "2. Redirect URI points to localhost instead of backend"
echo ""
echo "🔧 Required fixes:"
echo ""
echo "1. Go to: https://console.cloud.google.com/apis/credentials?project=$PROJECT_ID"
echo "2. Find OAuth 2.0 Client ID: $CLIENT_ID"
echo "3. Click 'Edit' (pencil icon)"
echo "4. Under 'Authorized redirect URIs':"
echo "   - Remove: http://localhost:3000/callback"
echo "   - Add: https://manage-tokens-vccbnr2zwa-uc.a.run.app/api/gmail/callback"
echo "5. Save the changes"
echo ""
echo "🔧 Backend environment variables to check:"
echo "The backend needs these environment variables set correctly:"
echo "   GOOGLE_CLIENT_ID=$CLIENT_ID"
echo "   GOOGLE_CLIENT_SECRET=[your-client-secret]"
echo "   REDIRECT_URI=https://manage-tokens-vccbnr2zwa-uc.a.run.app/api/gmail/callback"
echo ""
echo "⚠️  The newline character in client_id suggests the backend has a config issue."
echo "   The backend developer should check their environment variables."
echo ""
echo "🧪 After fixing, test at: http://localhost:3000/oauth-test"