# backend/dbt/cloudbuild.yaml
options:
  logging: CLOUD_LOGGING_ONLY

steps:
- id: "Install dbt"
  name: "python:3.9-slim"
  entrypoint: bash
  args:
    - "-c"
    - |
      pip install dbt-bigquery

- id: "Run dbt"
    name: "python:3.9-slim"
    entrypoint: bash
    dir: "."            # backend/dbt/
    args:
      - "-c"
      - |
        pip install dbt-bigquery && \
        dbt run --profiles-dir . --target dev
