# backend/dbt/cloudbuild.yaml
steps:
- id: "Install dbt"
  name: "python:3.9-slim"
  entrypoint: bash
  args:
    - "-c"
    - |
      pip install dbt-bigquery

- id: "Run dbt"
  name: "python:3.9-slim"
  entrypoint: bash
  dir: "."            # relative to where cloudbuild.yaml lives (backend/dbt/)
  args:
    - "-c"
    - |
      dbt run --profiles-dir . --target dev

