# backend/dbt/cloudbuild.yaml
steps:
  - id: "run-dbt"
    name: "python:3.9-slim"
    entrypoint: "bash"
    dir: "."              # relative to cloudbuild.yaml, so this is backend/dbt/
    args:
      - "-c"
      - |
        pip install dbt-bigquery && \
        dbt run --profiles-dir . --target dev

options:
  logging: CLOUD_LOGGING_ONLY
