# backend/dbt/cloudbuild.yaml
options:
  logging: CLOUD_LOGGING_ONLY

steps:
- id: "Install & run dbt"
  name: "python:3.9-slim"
  entrypoint: "bash"
  args:
    - "-c"
    - |
      # 1) install dbt
      pip install dbt-bigquery && \
      # 2) switch into your dbt folder (regardless of how Cloud Build clones it)
      cd backend/dbt && \
      # 3) run your models
      dbt run --profiles-dir . --target dev
timeout: "600s"
